### ISSUE TITLE
[Debian based] error: failed to run custom build command for `alsa-sys v0.1.1`

### ISSUE THREAD

**Issue by MahamdiAmine** [ritiek/piano-rs#24]

**Comment by ritiek** [comment]
Can you try again after `sudo apt install libasound2-dev`?

**Comment by schneiderfelipe** [comment]
Thanks @ritiek, your suggestion has solved it for me (Ubuntu 17.10).

**Comment by ritiek** [comment]
@dudektria Nice. I think more people might face this problem. Do you mind making a PR to add this note in the README?

**Comment by schneiderfelipe** [comment]
Sure.

**Comment by ritiek** [comment]
@MahamdiAmine If `libasound2-dev` package does not fix it for you, feel free to re-open this issue.

**Comment by Bietola** [comment]
I am having this exact problem (but with a different alsa-sys version), and I am not able to apply the proposed solution (as I am using Manjaro). Should I reopen this issue?

**Comment by ritiek** [comment]
@Bietola Let's just open a new issue for this.

**Comment by Bietola** [comment]
@ritiek ok, should I do it?
