### ISSUE TITLE
error: failed to run custom build command for `termbox-sys v0.2.10

### ISSUE THREAD

**Issue by jsomedon** [ritiek/piano-rs#27]
Got this error during build:

```
error: failed to run custom build command for `termbox-sys v0.2.10`
process didn't exit successfully: `/home/shong/Developer/piano-rs/target/release/build/termbox-sys-564ea512af8dd516/build-script-build` (exit code: 101)
--- stdout
running: "git" "clone" "https://github.com/nsf/termbox" ".termbox"
waf configure: setting CFLAGS to: `-m64 -fPIC`
running: "./waf" "configure" "--prefix=/"
Traceback (most recent call last):
  File "/home/shong/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Node.py", line 285, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shong/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Scripting.py", line 98, in waf_entry_point
    run_commands()
  File "/home/shong/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Scripting.py", line 155, in run_commands
    parse_options()
  File "/home/shong/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Scripting.py", line 128, in parse_options
    Context.create_context('options').execute()
  File "/home/shong/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Options.py", line 138, in execute
    super(OptionsContext,self).execute()
  File "/home/shong/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/shong/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/home/shong/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/.termbox/wscript", line 11, in options
    opt.load('compiler_c')
  File "/home/shong/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Context.py", line 89, in load
    fun(self)
  File "/home/shong/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Tools/compiler_c.py", line 36, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/home/shong/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Context.py", line 296, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/home/shong/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Node.py", line 334, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/home/shong/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/.termbox/.waf3-1.8.0-5c05be2d0e42d5c2c81403948a2d295b/waflib/Node.py", line 334, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration

--- stderr
Cloning into '.termbox'...
thread 'main' panicked at 'assertion failed: cmd.stdout(Stdio::inherit()).stderr(Stdio::inherit()).status().unwrap().success()', /home/shong/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/build.rs:87:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by ritiek** [comment]
Hi. I'll need more information here. What is your rustc and python version?
```
$ rustc -V
$ python -V
```

**Comment by jsomedon** [comment]
```
$ rustc -V
rustc 1.28.0 (9634041f0 2018-07-30)
$ python -V
Python 3.7.0
```

Hmm, see you are mentioning python, and maybe I should try with python2.
---EDIT
It compiles! But there is no sound when I press keys, I even tried like -v 10..

**Comment by ritiek** [comment]
Yep, Googling this seems like a known problem with Python 3.7. Using Python 2 should probably workaround this.

Do you have Python 2 already installed?

```
$ which python2
```

If so, try creating a symbolic link so that `$ python` launches Python 3:

```
$ sudo mv /usr/bin/python ~/python
$ sudo ln -s `which python2` /usr/bin/python
$ cargo clean
$ cargo build --release
```

If it installs correctly, you could then move your actual python back to its place:

```
$ sudo mv ~/python /usr/bin/python
```

I'm at the moment not near my lappy so I can't test this out. Let me know how it goes!

**Comment by ritiek** [comment]
That's great to know! There's also another issue about no sound (#6). See if it helps you.

**Comment by jsomedon** [comment]
Aha! So just like @darrenldl said in https://github.com/ritiek/piano-rs/issues/6#issuecomment-354971861, running `piano-rs` in a directory containing `asset` folder works. Interesting.

As no sound issue is already tracked in #6 and build error is resolved by linking `python` to `python2` let's close this issue. I recommend revise build guide to inform future users about this build issue though.

**Comment by ritiek** [comment]
> I recommend revise build guide to inform future users about this build issue though.

I'd appreciate a PR for this if you would like to. :)

**Comment by jsomedon** [comment]
No problem, there you go. English isn't my first language, let me know if wordings are ok.

**Comment by ritiek** [comment]
Thank you. :)

> English isn't my first language, let me know if wordings are ok.

No worries. Your English looks alright to me.

By the way, I also reported this issue in https://github.com/nsf/termbox/issues/117.

**Comment by ANCXY** [comment]
Could not compile `termbox-sys`. And I got the report :
```
error: could not find native static library 'termbox', perhaps an -L flag is missing?
error: aborting due to previous error
error: Could not compile 'termbox-sys'.

Caused by:
  process didn't exit successfully: 'rustc --crate-name termbox_sys /home/$user/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.11/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=eb4d5fa4c245464c -C extra-filename=-eb4d5fa4c245464c --out-dir /home/$user/Games/piano-rs/target/release/deps -L dependency=/home/$user/Games/piano-rs/target/release/deps --cap-lints allow -L /home/$user/Games/piano-rs/target/release/build/termbox-sys-26f724f97a589134/out/lib -l static=termbox' (exit code: 1)
```
 I  tried  
``` 
cd  ~/Games/piano-rs/target/release/build/termbox-sys-26f724f97a589134/out/ 
 ls
```
found there is only a directory named *lib64*, I changed it to *lib*,and it worked.

**Comment by DIvkov575** [comment]
does termbox depend on python2? because im on an apple silicon mac and those versions (of python) are not supported.

**Comment by ritiek** [comment]
@DIvkov575 Hi. Are you unable to compile piano-rs? If so, I'll be interested to look into the traceback you're getting. Also what's your rustc and python version at the moment?

**Comment by DIvkov575** [comment]
@ritiek The project im compiling this for is not piano.rs, however, I noticed the issue is in the compilation of dependency (termbox) and that I was getting the same exact errors as those mentioned in this thread. Im running python 3.10.10 and rustc 1.69.0-nightly

The full backtrace for running cargo build --release within the termbox dir is below

error: failed to run custom build command for `termbox-sys v0.2.10 (/Users/dmitriyivkov/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/dmitriyivkov/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/target/release/build/termbox-sys-d8374330ccf058cb/build-script-build` (exit status: 101)
  --- stdout
  waf configure: setting CFLAGS to: `-fPIC`
  running: cd "/Users/dmitriyivkov/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/.termbox" && "./waf" "configure" "--prefix=/"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:91:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/core/src/panicking.rs:64:14
     2: core::result::unwrap_failed
               at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/core/src/result.rs:1790:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::run
     5: build_script_build::configure
     6: build_script_build::main
     7: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[ritiek](https://github.com/ritiek)
