### ISSUE TITLE
panicked at 'called Result::unwrap() on an Err

### ISSUE THREAD

**Issue by andy5995** [ritiek/piano-rs#40]
I cloned from git, built with `cargo --build`.

* OS: Debian 10
* Rust version: rustc 1.47.0 (18bf6b4f0 2020-10-07)

I got a short error message each time I ran the program (reproduced 3 times) after pressing keys at random, one at a time. So I ran it using RUST_BACKTRACE=1 and got some extra detail.

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("invalid value: integer `4169265872`, expected variant index 0 <= i < 5")', src/network/receiver.rs:25:69
         stack backtrace:
                            0: rust_begin_unwind
                                                             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
                                                         1: core::panicking::panic_fmt
                                                                                                   at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
     2: core::option::expect_none_failed
                                                     at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
                                                3: core::result::Result<T,E>::unwrap
                                                                                                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/result.rs:973
                                                                                           4: piano_rs::network::receiver::Receiver::poll_event
                                                                  at ./src/network/receiver.rs:25
          5: piano_rs::handle_network_receive_event
                                                                at ./src/main.rs:37
                                                                                      6: piano_rs::main::{{closure}}
                                       at ./src/main.rs:135
                                                           note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by jmanabc** [comment]
I have the same issue on Manjaro with rust 1.48.0

**Comment by ritiek** [comment]
This is weird. I'm not really sure what would be causing this. Can you guys provide more information on how exactly are you running the game?

> I have the same issue on Manjaro with rust 1.48.0

I'm on Manjaro at the moment too and `$ rustc -V` gives me `rustc 1.48.0 (7eac88abb 2020-11-16)`, but I am able to compile and played music for 10 minutes straight without any problem with:
```
$ git clone https://github.com/ritiek/piano-rs
$ cd piano-rs
$ cargo run --release
```

Also, is there any pattern to when the traceback happens? Or does it apparently happen randomly on some key press?

**Comment by andy5995** [comment]
No pattern that I could tell.. Happens within a minute.

Here's the output when I run `RUST_BACKTRACE=full ./target/debug/piano-rs`

https://gist.githubusercontent.com/andy5995/70ae708a3a32ba90e0325edf35ce42db/raw/12a7e2a66656840d91a18dfe78e7738679f0a57b/gistfile1.txt

And the output when I run `RUST_BACKTRACE=full ./target/release/piano-rs` (after using `cargo build --release`)

https://gist.githubusercontent.com/andy5995/d4e533fdfdaea37adc417490f681c730/raw/9d4d775909c2ebf4437a78a996278b42d12c1d9a/gistfile1.txt

I'm trying git rev 00f6c64 and building now with rustc 1.48.0 (7eac88abb 2020-11-16)

**Comment by andy5995** [comment]
I tried with the '-r' option. Another crash, but here are the recorded notes

https://gist.githubusercontent.com/andy5995/b6ce15841c0e1c98e7cb76e286a872a6/raw/96b5c2635d01ff6126a012f55bb74c8289a381e9/gistfile1.txt

On another try, crashed after only a few notes

```
note_1:
  - 1513
  - gs1
  - 0

note_2:
  - 671
  - as1
  - 0

note_3:
  - 1984
  - cs2
  - 0

```

**Comment by andy5995** [comment]
@ritiek I suggest that you run `cargo clippy`. I get over 30 warnings when I do that. Maybe fixing some of them would make it easier to debug.

**Comment by ritiek** [comment]
Alright, I see.

> @ritiek I suggest that you run `cargo clippy`. I get over 30 warnings when I do that. Maybe fixing some of them would make it easier to debug.

Ok, will do this.

**Comment by ritiek** [comment]
Could you guys try building it again from master branch? I fixed the clippy warnings and updated a few dependencies too, so let's see how that affects the traceback just in case if it does.

**Comment by andy5995** [comment]
Sorry to tell you, I have the same problem.

Here's some extra info (maybe it'll help troubleshooting later?)

```
andy@oceanus:~/src/rust/piano-rs/target/release$ ldd piano-rs
	linux-vdso.so.1 (0x00007ffd10bc0000)
	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007fa834c83000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa834c69000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa834aa8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa834f59000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa834925000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa834904000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa8348ff000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa8348f3000)
```

**Comment by ritiek** [comment]
Could you try passing `--receiver-address=127.0.0.1:6347`. It could be possible that the default bind address of `0.0.0.0:9999` is receiving data from another source (piano-rs does not validate this data at the moment so it should probably crash like it does in your case).

**Comment by andy5995** [comment]
No change. You might be able to reproduce the issue by pressing the semicolon or 'd' key while you're testing (the crash won't happen immediately).

**Comment by ritiek** [comment]
So weird. Still can't reproduce with what you suggested.

**Comment by andy5995** [comment]
Also happens when I play back a recorded file, but not every time. so far about 2/4 times. I first recorded the file and exited piano-rs with ESC before it crashed.

It played the notes, then after about 5-10 seconds, I got the error.

https://user-images.githubusercontent.com/16764864/102729233-7f97af00-42f5-11eb-905a-b2b93355cb11.mp4

```
note_1:
  - 2518
  - as2
  - 0

note_2:
  - 370
  - b2
  - 0

note_3:
  - 392
  - as2
  - 0

note_4:
  - 583
  - a2
  - 0

note_5:
  - 440
  - gs2
  - 0

note_6:
  - 415
  - g2
  - 0

note_7:
  - 479
  - as2
  - 0

note_8:
  - 399
  - b2
  - 0

note_9:
  - 368
  - as2
  - 0

note_10:
  - 431
  - a2
  - 0

note_11:
  - 392
  - gs2
  - 0

note_12:
  - 431
  - g2
  - 0
```

cc @jammyjamjamman

**Comment by Jammyjamjamman** [comment]
Me and Andy used tcpdump to listen to the udp port the piano binds to, while using the piano. We could see the packets that are sent when pressing piano keys. However, interestingly, the rouge packet the piano kept receiving on Andy's computer was not picked up by tcpdump.

So the piano game is picking up data in the udp buffer, but it's unclear where it's coming from. We modified the piano program to spit out the `buf` contents in the receiver, when it causes the bincode decoder to panic. This is the content of the buffer when it causes the piano receiver on Andy's computer to crash:

```
[D0, F2, 81, F8, 8B, FF, 9A, F7, D5, EF, 94, B6, D1, B4, C0, 9F, EC, 95, E6, 8F, E1, 87, E8, CA, F0, 8B, F6, 8B, F6, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
```

(N.b. I cannot reproduce this bug on my laptop, running Manjaro, kernel 5.9-11, rustc 1.48.0.)

**Comment by andy5995** [comment]
I've found I can reproduce the bug more predictably if I wait between key presses. Sometimes if I start the program and press no key, it will crash in ~10-120 seconds. Sometimes if I press one key, then wait several seconds it will crash. Or pressing 2 keys within ~10 seconds, then pressing no keys, a crash will happen.

**Comment by ritiek** [comment]
Interesting. What do you see when you print the value of ``src` in https://github.com/ritiek/piano-rs/blob/5509a9e4e2204169c2234ca279089aaac942d314/src/network/receiver.rs#L23

Either way, I'll add checks to make sure to proceed only if the network data received is valid. That should probably fix this.

**Comment by andy5995** [comment]
@ritiek @Jammyjamjamman found that some packets from another device on my network were interfering. It turned out to be my Google Home mini. After I blocked its IP on my LAN, he couldn't reproduce the crash.

Note that I was still crashing before when trying your suggestion of using '--receiver-address=127.0.0.1:6347'... so I guess the Google thing was sending packets to quite a variety of ports!

**Comment by ritiek** [comment]
@andy5995 Could you try replacing this function here:

https://github.com/ritiek/piano-rs/blob/5509a9e4e2204169c2234ca279089aaac942d314/src/network/receiver.rs#L19-L31

with:
```rust
    pub fn poll_event(&self) -> Result<types::NetworkData> {
        self.socket.set_read_timeout(None)?;
        let mut buf = [0; 300];
        loop {
            let (amt, src) = self.socket.recv_from(&mut buf)?;
            let result = bincode::deserialize(&buf);
            if let Ok(event) = result {
                break Ok(types::NetworkData {
                    amt,
                    src,
                    event,
                })
            }
        }
    }
```
and see whether the piano still panics when google home is online in the same network?

**Comment by andy5995** [comment]
Your patch works. Nice job.

btw, in case this info is helpful for debugging in the future, here's how to reproduce the crash (before your patch is applied) without a Google assistant:

* start piano-rs
* In another terminal, run 'echo -n "hello world" | nc -u -v -q20 <IP> 9999'

(see [nc/netcat](https://stackoverflow.com/q/9696129/6838037) or [netcat on Wikipedia](https://en.wikipedia.org/wiki/Netcat))

Where IP is an IP that piano-rs is listening on. I tested using the IP of my wlan interface.

Before the patch, I used [iptraf-ng](https://github.com/iptraf-ng/iptraf-ng/) and saw that Google was indeed shooting packets to port 9999. I don't know why your earlier suggestion of using `--receiver-address=127.0.0.1:6347` didn't work for me (maybe I used 0.0.0.0 instead of 127.0.0.1).

G appears to be broadcasting to these ports many times within 60 seconds, repeatedly: 9999, 10101, and 5353

**Comment by ritiek** [comment]
> Your patch works. Nice job.

Good to know! I'll push it to master.

> I don't know why your earlier suggestion of using `--receiver-address=127.0.0.1:6347` didn't work for me (maybe I used 0.0.0.0 instead of 127.0.0.1).

Yep. That should've worked with `0.0.0.0` too as long no data is being received on that port. No idea why it didn't. Anyway, thanks for providing information on how to debug this, it's gonna be useful in future!
