### ISSUE TITLE
Spontaneous demo video

### ISSUE THREAD

**Issue by andy5995** [ritiek/piano-rs#41]
I recorded a spontaneous demo video with @jammyjamjamman

https://www.twitch.tv/videos/845867685

@ritiek Have you considered enabling the "Discussions" setting on your repo?

**Comment by ritiek** [comment]
Nice! If it could be a shorter ~1 or 2 minutes screencast, I'll be happy to share it in the README.

> @ritiek Have you considered enabling the "Discussions" setting on your repo?

Not really. I like to avoid using GitHub's monopolistic features (when compared to Gitea or other git hosting services), so I can have an easy time migrating all my stuff in case I decide I'm done with GitHub.

**Comment by andy5995** [comment]
Clip added in #42
