### ISSUE TITLE
Make the program search at "/usr/share/piano-rs"

### ISSUE THREAD

**Issue by hardBSDk** [ritiek/piano-rs#50]
This program should search the assets at `~/.local/share/piano-rs` or `/usr/share/piano-rs`

It's necessary to package the program on operating systems.

**Comment by ritiek** [comment]
Hi, thanks for reaching out! it's been a while since i worked on piano-rs. I'll try to see how much effort this'll be the coming weekend.

**Comment by ritiek** [comment]
It'll now search for note files in order of preference https://github.com/ritiek/piano-rs/commit/69ddb5616438bf97fd2ec2aa7c653e9abaccf192. Is this good enough?

If there's anything else required to be done on my part, happy to help.

**Comment by hardBSDk** [comment]
@ritiek That's good, you could use `/usr/share/piano-rs` because the configuration folder seems to store only notes, right? thus there's no need for an "assets" folder.

**Comment by ritiek** [comment]
Yep, that's right. Felt it'd be nice to have "assets" folder just in case there's some other stuff that might get introduced in piano-rs in the future and would have to be persisted, then it wouldn't have to be mixed up in so many music files. What do you think?

**Comment by hardBSDk** [comment]
@ritiek That's enough, thanks for implementing this!
